server:
  port: 8888
management:
  context_path: /admin


spring:

  application:
    name: spring-config-server-demo
  cloud:
    config:
      server:
        git:
          searchPaths: /share
          uri: https://github.com/dragontree101/dragon-config-repo
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme