server:
  port: 8888
management:
  context_path: /admin


spring:

  application:
    name: spring-config-server-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dragontree101/dragon-config-repo
          development:
            pattern:
              - development
            uri: https://github.com/dragontree101/dragon-config-repo
          production:
            pattern:
             - production
            uri: https://github.com/dragontree101/dragon-config-repo

encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme